language: en-US

issue_enrichment:
  auto_enrich:
    enabled: true
  labeling:
    auto_apply_labels: true
  related_issues:
    enabled: true
  related_prs:
    enabled: true
  duplicate_detection:
    enabled: true
# test
